### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodmallet_web_frontend#17]
```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/general_website/views/general.py", line 539, in get_chart_data
    json_data = json.load(data)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by Bloodmallet** [comment]
Should be fixed.
